# Generated by Django 3.0.6 on 2020-05-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='BPmeds',
            field=models.IntegerField(null=True),
        ),
    ]
